CREATE DATABASE AGRIENERGY;
USE AGRIENERGY;

CREATE TABLE USERS (
    USER_ID INT IDENTITY(1, 1) PRIMARY KEY,
    FIREBASE_UID VARCHAR(100) UNIQUE, -- Unique identifier from Firebase
    ROLE VARCHAR(10), -- 'EMPLOYEE' or 'FARMER'
    NAME VARCHAR(100),
    DOB DATE,
    BIO TEXT
);

CREATE TABLE CATEGORIES (
    CATEGORY_ID INT IDENTITY(1, 1) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) UNIQUE
);
ALTER TABLE CATEGORIES
ADD IMAGE_URL VARCHAR(255);

SELECT * FROM CATEGORIES

INSERT INTO CATEGORIES (CATEGORY_NAME, IMAGE_URL)
VALUES ('Fruits', 'https://assets-global.website-files.com/5f6cc9cd16d59d990c8fca33/64c97a533d276d58c28b32a4_list-of-fruits.jpg');


CREATE TABLE PRODUCTS (
    PRODUCT_ID INT IDENTITY(1, 1) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    PRODUCT_DESCRIPTION VARCHAR(8000),
    PRICE FLOAT,
    QUANTITY INT,
    AVAILABILITY VARCHAR(3), -- 'YES' or 'NO'
    PRODUCTION_DATE DATE,
    FARMER_ID INT, -- FK to USERS table
    CATEGORY_ID INT, -- FK to CATEGORIES table
    FOREIGN KEY (FARMER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE CART(
CART_ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_ID INT
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
);






DROP TABLE CART



ALTER TABLE PRODUCTS
ADD IMAGE_URL VARCHAR(255); -- Adjust the data type and length as needed

SELECT * FROM USERS
DELETE FROM USERS WHERE USER_ID LIKE 2

ALTER TABLE USERS
ALTER COLUMN FIREBASE_UID VARCHAR(500); -- Adjust the length as needed

EXEC sp_columns USERS;

SELECT * FROM PRODUCTS
SELECT * FROM CATEGORIES
SELECT * FROM CART
SELECT * FROM USERS